### ISSUE TITLE
Blurry Pixel Art at Higher Resolutions

### ISSUE THREAD

**Issue by Kaillr** [Nocturnal-Skirmish/Nocturnal-Skirmish-GameHub#10]
The card images and profile border images currently appear blurry when viewed at resolutions higher than their original size. This issue likely impacts the user experience by making the images look unpolished or low-quality.

### Example

See the image below for reference. The blurring is noticeable when the images are scaled up:

![image](https://github.com/user-attachments/assets/cd0f92f0-b6f2-42c4-a243-1cfc456a235a)

## Suggested fix

In order to fix this issue apply `image-rendering: pixelated;` to all the pixel art images. This will ensure that they scale correctly without losing their sharpness or becoming blurry.

### Code Example:

```css
.pixel-art {
    image-rendering: pixelated;
    image-rendering: crisp-edges; /* Fallback for other browsers */
}
```

### Expected outcome

After applying the fix, scaled images should retain their clarity and match the intended visual style. Here’s an example of the expected result:

![image](https://github.com/user-attachments/assets/f5d9be88-df85-4064-89da-3a975fe498ba)
